---
version: "3"

dotenv:
  - ".env"

interval: 500ms

vars:
  POSTGRESQL_HOST: $POSTGRESQL_HOST
  POSTGRESQL_PORT: $POSTGRESQL_PORT
  POSTGRESQL_USER: $POSTGRESQL_USER
  POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
  POSTGRESQL_DATABASE_NAME: $POSTGRESQL_DATABASE_NAME
  SERVICE_NAME: server2
  MIGRATIONS_DIR: ./db/postgresql/migrations
  DATABASE_URL: postgres://{{.POSTGRESQL_USER}}:{{.POSTGRESQL_PASSWORD}}@{{.POSTGRESQL_HOST}}:{{.POSTGRESQL_PORT}}/{{.POSTGRESQL_DATABASE_NAME}}?sslmode=disable

tasks:
  tidy:
    desc: runs go mod tidy
    cmds:
      - go mod tidy

  build:
    desc: builds the project
    cmds:
      - task: sqlc-generate
      - go build -o ./dist/main main.go

  run:
    desc: run main.go file
    cmds:
      - go run main.go

  dev:
    desc: dev
    cmds:
      - air

  sqlc-generate:
    desc: generate sqlc code
    cmd: sqlc generate

  migration-new:
    desc: Create new migration
    summary: Use - task new-migration -- "create_table_author"
    cmd: migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.CLI_ARGS}}

  migration-drop:
    desc: Drop everything inside database
    cmd: migrate -source file://{{.MIGRATIONS_DIR}} -database {{.DATABASE_URL}} -verbose drop -f

  migration-up:
    desc: Run migrations up
    cmd: migrate -source file://{{.MIGRATIONS_DIR}} -database {{.DATABASE_URL}} -verbose up

  migration-down:
    desc: Run migrations down
    cmd: migrate -source file://{{.MIGRATIONS_DIR}} -database {{.DATABASE_URL}} -verbose down -all
