---
version: "3.8"

networks:
  proxy:
    external: true

services:
  talkverse-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkverse-frontend
    networks:
      - proxy
    ports: [4173:4173] # disable in production
    env_file: .env
