---
version: "3.8"

networks:
  # NOTE: In production use nginx-proxy internal network
  proxy:
    external: true

services:
  talkverse-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkverse-frontend
    networks:
      - proxy
    ports: [4173:4173] # NOTE: disable in production
    env_file: .env
