
services:
  talkverse-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkverse-client
    networks:
      - proxy
    ports: [4173:4173] # NOTE: disable in production
    env_file: .env

networks:
  # NOTE: In production use nginx-proxy internal network
  proxy:
    external: true
