---
version: '3.8'

x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

volumes:
  talkverse-app:
  talkverse-pg:
  talkverse-mongo:

networks:
  talkverse-proxy:
  proxy:
    external: true

services:
  # ---
  app:
    <<: *x-logging
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkverse-app
    volumes:
      - talkverse-app:/usr/src/app
    networks:
      - talkverse-proxy
    ports: [5000:5000]
    depends_on:
      - postgres
      - mongo

  postgres:
    <<: *x-logging
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: talkverse-postgres
    image: postgres:16-alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - talkverse-pg:/var/lib/postgresql/data
    networks:
      - talkverse-proxy
    ports: [5432:5432]

  mongo:
    <<: *x-logging
    restart: unless-stopped
    container_name: talkverse-mongo
    image: mongo:5.0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - talkverse-mongo:/var/lib/mongodb/data
    networks:
      - talkverse-proxy
    ports: [27017:27017]