---
version: '3.8'

volumes:
  talkverse-backend:
  talkverse-postgres-db:
  talkverse-mongo-db:

networks:
  talkverse-proxy:
  proxy:
    external: true

services:
  talkverse-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkverse-backend
    volumes:
      - talkverse-backend:/usr/src/app
    networks:
      - talkverse-proxy
      - proxy
    ports: [5000:5000] # disable in production
    env_file: .env
    depends_on:
      - postgres
      - mongo
    entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
    command: [ 'node', 'dist/index.js']

  postgres:
    container_name: talkverse-postgres
    image: postgres:16-alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - talkverse-postgres-db:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - talkverse-proxy
    # ports: [5432:5432]

  mongo:
    container_name: talkverse-mongo
    image: mongo:7.0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - talkverse-mongo-db:/var/lib/mongodb/data
    env_file: .env
    networks:
      - talkverse-proxy
    # ports: [27017:27017]