---
version: '3.8'

networks:
  talkverse-backend-proxy:
    external: true

services:
  talkverse-kafka-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkverse-kafka-consumer
    networks:
        - talkverse-backend-proxy
    env_file: .env
  stop_grace_period: 20s