export const clientE = {

    USER_REQUEST: "USER_REQUEST",
    REQUEST_ACCEPTED: "REQUEST_ACCEPTED",

    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    GROUP_MESSAGE_RECIEVED: "GROUP_MESSAGE_RECIEVED",

    OTHER_START_TYPING: "OTHER_START_TYPING",
    OTHER_STOP_TYPING: "OTHER_STOP_TYPING",

    SET_USER_ONLINE: "SET_USER_ONLINE",
    SET_USER_OFFLINE: "SET_USER_OFFLINE",
    ADDED_IN_GROUP: "ADDED_IN_GROUP"
};

export const serverE = {

    SEND_MESSAGE: "SEND_MESSAGE",
    SEND_GROUP_MESSAGE: "SEND_GROUP_MESSAGE",

    START_TYPING: "START_TYPING",
    STOP_TYPING: "STOP_TYPING",
};