export const ce = {
    USER_REQUEST: "USER_REQUEST",
    REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    OTHER_START_TYPING: "OTHER_START_TYPING",
    OTHER_STOP_TYPING: "OTHER_STOP_TYPING",
    UNSEEN_CHAT_COUNT: "UNSEEN_CHAT_COUNT",
    SET_USER_ONLINE: "SET_USER_ONLINE",
    NEW_CHAT_BAR_DATA: "NEW_CHAT_BAR_DATA",
    ADDED_IN_GROUP: "NEW_CHAT_BAR_DATA"
};

export const se = {
    SEND_MESSAGE: "SEND_MESSAGE",
    START_TYPING: "START_TYPING",
    STOP_TYPING: "STOP_TYPING",
};